# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8-u355rW2l-tr75CHcpn60ftSZur4Ck
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

la = ['숭실대학교', '서울시 동작구 상도동']

la[0]

la.index('숭실대학교')

la.append('02-828-0000')

la

del la[2]

la

len(la)

npi = np.random.rand(10)*10

npi = map(int, npi)

npi = list(npi)

for n in range(10):
  c = npi.count(n)
  print('%d: %d' %(n, c))

dic = {'a': 1, 'b':10, 'c':11, 'd':13}

type(dic)

dic['a']

#list --> append
dic['e'] =  12

dic

del dic['e']

dic

kdic = dic.keys()

kdic
kdicl = list(kdic)
kdicl

